sudo: required
language: java

jdk:
  - openjdk8

services:
  - docker

script:
  - travis_wait ./gradlew check --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
    - ./gradlew jacocoTestReport coveralls